server:
  port: 9000

management:
  endpoint:
    health:
      enabled: true

logging.level.org.springframework.security: DEBUG

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resource:
        token-info-uri: http://localhost:8080/oauth/check_token
