server:
  port: 9000

management:
  endpoint:
    health:
      enabled: true

logging.level.org.springframework.security: DEBUG

spring:
  application:
    name: resource-server
  security:
    oauth2:
      client:
        clientId: user-client
        clientSecret: user-secret-8888
      resource:
        tokenInfoUri: https://localhost:8080/oauth/check_token
